shellEmulator: true

trustPolicy: no-downgrade

packages:
  - . # TODO add for running `pnpm i` correctly for now, if it's not added, `pnpm i` will fail. Remove it when planning to add real workspace packages.

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
